---
title: frap_fire_perimeter
author: Angela Zhao
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(sf)
library(ussf)

# Parameters
file_raw <- here::here("data-raw/frap_fire_perimeter_gis.gdb")

CA_ALBERS <- 
  "+proj=aea +lat_1=34 +lat_2=40.5 +lat_0=0 +lon_0=-120 +x_0=0 +y_0=-4000000 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

```

## Reading in Fire Perimeter Data

```{r}

layers <-
  file_raw %>% 
  st_layers()

read_sf_layers <- function(name) {
  file_raw %>% 
    read_sf(layer = name)
}

map(layers$name, read_sf_layers)

```
## Checking if first layer already in layer 2

```{r}
layers$name

fire_shape <- 
  file_raw %>% 
  read_sf(layer = "Non_RXFire_Legacy13_2") %>% 
  rename_all(tolower) %>% 
  pull(shape)

non_rx_shape <-
  file_raw %>% 
  read_sf(layer = "firep19_1") %>% 
  rename_all(tolower) %>% 
  pull(shape)

setdiff(non_rx_shape, fire_shape)

```


## Wrangling Wildfire Data

```{r}
wildfires_2018_19 <-
  file_raw %>% 
  read_sf(layer = "firep19_1") %>% 
  rename_all(tolower) %>% 
  filter(alarm_date >= "2018-08-15", year_ %in% c("2018","2019"))

wildfires_2017_19 <-
  file_raw %>% 
  read_sf(layer = "firep19_1") %>% 
  rename_all(tolower) %>% 
  filter(alarm_date >= "2017-08-15", year_ %in% c("2018","2019"))
```

## Finding projection of wildfires

```{r}
st_crs(wildfires_2017_19)

st_crs(wildfires_2018_19)

```

## Plotting wildfires on top of California w/ CA Albers projection

```{r}
ca <-
  boundaries(geography = "state", resolution = "500k", projection = "albers") %>% 
  filter(NAME == "California") %>% 
  st_transform(crs = CA_ALBERS)

ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = wildfires_2017_19)

ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = wildfires_2018_19)


```
